---
title: "Reproducible Figures Assignment"
output:
  html_document: default
  pdf_document: default
date: "2023-11-29"
---

#Installing and loading packages
```{r}
library(tidyverse)
library(palmerpenguins)
library(janitor)
library(here)
library(ggplot2)
library(patchwork)
library(ragg)
library(svglite)

source(here("functions","cleaning_penguin_data.r"))
```

# Data Preparation:
```{r}
#Preserving and loading raw data.

write.csv(penguins_raw, here("data","penguins_raw.csv"))
penguins_data_raw<-read.csv(here("data","penguins_raw.csv"))


#Investigating data

head(penguins_data_raw)
colnames(penguins_data_raw)


#Cleaning raw data to generate a cleaner dataset.

cleaning_penguin_columns <- function(raw_data){
    raw_data %>% 
    clean_names() %>% 
    shorten_species() %>% 
      remove_empty(c("rows", "cols")) %>% 
      select(-starts_with("delta")) %>% 
      select(-comments)}
      
colnames(penguins_data_raw)
penguins_data_clean<-cleaning_penguin_columns(penguins_data_raw)
colnames(penguins_data_clean)

#writes new csv for clean penguins data. 
write.csv(penguins_data_clean, here("data","penguins_data_clean.csv"))
```

### QUESTION 01: Data Visualisation for Science Communication

*Create a figure using the Palmer Penguin dataset that is correct but badly communicates the data. **Do not make a boxplot**.*
```{r bad figure code, echo=FALSE}
ggplot(data=penguins_data_clean, aes(x=body_mass_g, y=culmen_length_mm)) + geom_point()

agg_png("figures/bad_boxplot.png", width=20, height=20, units="cm", res=200, scaling=0.5)
```
